project_id: 762049
base_path: "."
base_url: "https://api.crowdin.com"
branch: "main"

#
# Choose file structure in crowdin
# e.g. true or false
#
preserve_hierarchy: false

#
# Files configuration
#
files: [
  {
    source: "/app/src/main/res/values/strings.xml",
    translation: "/app/src/main/res/values-%two_letters_code%/%original_file_name%"
  },
  {
    source: "/resources/playstore/play_store_description.txt",
    translation: "/resources/playstore/play_store_description_%android_code%.txt"
  }
]