name: Report Unit Test Results

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code for Annotations
        uses: actions/checkout@v4
      - name: Download Unit Test Results
        uses: actions/download-artifact@v4
        with:
          name: unit-test-results
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Report
          path: TEST-*.xml
          reporter: java-junit
